# @author nikoeleison

#--- settings

# enable color
set -g default-terminal "screen-256color"

# current path on new pane/window
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
